export const API_ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    setRole: (id) => `/auth/users/${id}/role`,
  },
  users: {
    list: '/users',
    get: (id) => `/users/${id}`,
    update: (id) => `/users/${id}`,
    remove: (id) => `/users/${id}`,
  },
  teachers: {
    list: '/teachers',
    get: (id) => `/teachers/${id}`,
    create: '/teachers',
    update: (id) => `/teachers/${id}`,
    remove: (id) => `/teachers/${id}`,
  },
  subjects: {
    list: '/subjects',
    get: (id) => `/subjects/${id}`,
    create: '/subjects',
    update: (id) => `/subjects/${id}`,
    remove: (id) => `/subjects/${id}`,
  },
  classes: {
    list: '/classes',
    get: (id) => `/classes/${id}`,
    create: '/classes',
    update: (id) => `/classes/${id}`,
    remove: (id) => `/classes/${id}`,
  },
  rooms: {
    list: '/rooms',
    get: (id) => `/rooms/${id}`,
    create: '/rooms',
    update: (id) => `/rooms/${id}`,
    remove: (id) => `/rooms/${id}`,
  },
  periods: {
    list: '/periods',
    get: (id) => `/periods/${id}`,
    create: '/periods',
    update: (id) => `/periods/${id}`,
    remove: (id) => `/periods/${id}`,
  },
  tasks: {
    list: '/tasks',
    get: (id) => `/tasks/${id}`,
    create: '/tasks',
    update: (id) => `/tasks/${id}`,
    cancel: (id) => `/tasks/${id}/cancel`,
    remove: (id) => `/tasks/${id}`,
    assignments: (id) => `/tasks/${id}/assignments`,
    myAssignments: '/tasks/assignments/mine',
    allAssignments: '/tasks/assignments/all',
    updateAssignment: (id) => `/tasks/assignments/${id}/status`,
    markOverdue: '/tasks/mark-overdue',
  },
  leave: {
    list: '/leave',
    get: (id) => `/leave/${id}`,
    submit: '/leave',
    approve: (id) => `/leave/${id}/approve`,
    reject: (id) => `/leave/${id}/reject`,
    proxy: {
      list: '/leave/proxy',
      create: '/leave/proxy',
      approve: (id) => `/leave/proxy/${id}/approve`,
      reject: (id) => `/leave/proxy/${id}/reject`,
    },
  },
  timetable: {
    active: '/timetable',
    history: '/timetable/history',
    save: '/timetable/save',
    publish: '/timetable/publish',
    publishById: (id) => `/timetable/${id}/publish`,
    settings: '/timetable/settings',
  },
  attendance: {
    list: '/attendance',
    get: (id) => `/attendance/${id}`,
    mark: '/attendance',
    update: (id) => `/attendance/${id}`,
  },
  fees: {
    list: '/fees',
    mine: '/fees/me',
    get: (id) => `/fees/${id}`,
    create: '/fees',
    update: (id) => `/fees/${id}`,
    remove: (id) => `/fees/${id}`,
  },
  reports: {
    list: '/reports',
    get: (id) => `/reports/${id}`,
    create: '/reports',
    remove: (id) => `/reports/${id}`,
  },
};
